name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --workspace --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Lint
      run: cargo clippy --workspace --all-targets -- --deny clippy::all --deny clippy::pedantic --deny clippy::nursery
    - name: Format
      run: cargo fmt --check
